/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Report that the process is running. Performs no dependency work.
         */
        get: operations["liveness_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Aggregate the readiness-check registry and set the HTTP status.
         *
         *     Returns ``503`` when any dependency check fails so orchestrators treat the
         *     instance as not-ready without parsing the body.
         */
        get: operations["readiness_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Non-secret runtime configuration
         * @description Return runtime configuration safe to expose to any client.
         *
         *     Secrets, API keys, and connection strings are never included.
         */
        get: operations["config_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create or update a patient by phone
         * @description Upsert by phone: ``201`` when created, ``200`` when an existing row is updated.
         */
        post: operations["upsert_patient_patients_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/{patient_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a patient by id
         * @description Return a patient by UUID, or ``404`` if absent.
         */
        get: operations["get_patient_patients__patient_id__get"];
        put?: never;
        post?: never;
        /**
         * Erase a patient (PDPA right to erasure)
         * @description Hard-delete a patient and cascade appointments, sessions, and messages.
         */
        delete: operations["delete_patient_patients__patient_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/patients/by-phone/{phone}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve a patient by phone
         * @description Resolve identity by phone (E.164-normalized), or ``404`` if absent.
         */
        get: operations["get_patient_by_phone_patients_by_phone__phone__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List conversation threads for a patient
         * @description List a patient's threads, newest first. A ``phone`` or ``patient_id`` is required.
         */
        get: operations["list_sessions_sessions_get"];
        put?: never;
        /**
         * Create a conversation thread
         * @description Create a thread, associating a patient when the phone resolves.
         *
         *     An identified patient is capped at ``max_sessions_per_patient`` threads; over
         *     the cap the request is rejected with ``409`` rather than growing unbounded.
         */
        post: operations["create_session_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch a conversation thread
         * @description Fetch a thread; ``?include=messages`` embeds its messages.
         */
        get: operations["get_session_by_id_sessions__session_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete a conversation thread
         * @description Delete a thread and cascade its messages.
         */
        delete: operations["delete_session_sessions__session_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * One synchronous chat turn
         * @description Run the pipeline, persist the turn, close the CAG loop, and return the result.
         */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * One chat turn, streamed over SSE
         * @description Stream the same pipeline as ``routing``/``delta``/``final``/``error`` SSE events.
         */
        post: operations["chat_stream_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Read a session's message history
         * @description Return persisted messages for a session, oldest first, paginated.
         */
        get: operations["chat_history_chat_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/summarize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh a session's rolling summary
         * @description Compress the session's older turns into a bounded rolling summary.
         */
        post: operations["chat_summarize_chat_summarize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat/memory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Clear a session's short-term memory
         * @description Delete a session's messages and summary, keeping the session record.
         */
        delete: operations["chat_clear_memory_chat_memory_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prometheus metrics (operational, not a business endpoint)
         * @description Return the current metrics in Prometheus text exposition format.
         */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service landing
         * @description Return the service name and version. Not a counted API endpoint.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ChatHistoryResponse
         * @description Paginated message history for a session, oldest first.
         */
        ChatHistoryResponse: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Total */
            total: number;
            /** Messages */
            messages: components["schemas"]["ChatMessageResponse"][];
        };
        /**
         * ChatMessageResponse
         * @description A persisted message in the history read.
         */
        ChatMessageResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ChatRequest
         * @description Body for ``POST /chat`` and ``POST /chat/stream``.
         */
        ChatRequest: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Message */
            message: string;
            /**
             * Phone
             * @description Caller phone; resolved to identity.
             */
            phone?: string | null;
        };
        /**
         * ChatResponse
         * @description The structured result of one chat turn.
         */
        ChatResponse: {
            /** Verdict */
            verdict: string;
            /** Route */
            route: string | null;
            /** Answer */
            answer: string;
            /** Citations */
            citations: string[];
            structured: components["schemas"]["TableResponse"] | null;
            usage: components["schemas"]["UsageResponse"] | null;
            /** Latency Ms */
            latency_ms: number;
            /** Trace */
            trace: components["schemas"]["TraceEntryResponse"][];
        };
        /**
         * Check
         * @description The outcome of a single readiness dependency check.
         */
        Check: {
            /**
             * Name
             * @description Stable identifier for the dependency, e.g. 'postgres'.
             */
            name: string;
            /**
             * Ok
             * @description Whether the dependency is currently healthy.
             */
            ok: boolean;
            /**
             * Detail
             * @description Optional human-readable context, typically set when 'ok' is false.
             */
            detail?: string | null;
        };
        /**
         * ConfigResponse
         * @description Non-secret runtime configuration exposed for diagnostics and the UI.
         *
         *     This model intentionally contains no secrets, connection strings, or API
         *     keys. Only values safe to display to any client belong here.
         */
        ConfigResponse: {
            /** App Name */
            app_name: string;
            /** App Env */
            app_env: string;
            /** Version */
            version: string;
            /** Log Level */
            log_level: string;
            /**
             * Features
             * @description Feature-flag map describing which capabilities are enabled.
             */
            features?: {
                [key: string]: boolean;
            };
        };
        /**
         * ErrorDetail
         * @description The body of an error, identifying the class of failure.
         */
        ErrorDetail: {
            /**
             * Code
             * @description Stable, machine-readable error code.
             */
            code: string;
            /**
             * Message
             * @description Human-readable summary, free of personal data.
             */
            message: string;
            /**
             * Fields
             * @description Field-level details for validation errors; empty otherwise.
             */
            fields?: components["schemas"]["FieldError"][];
        };
        /**
         * ErrorEnvelope
         * @description The consistent error response shape returned by every endpoint.
         */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
        };
        /**
         * FieldError
         * @description A single field-level validation problem. Carries no submitted values.
         */
        FieldError: {
            /**
             * Field
             * @description Dotted path to the offending field.
             */
            field: string;
            /**
             * Message
             * @description Human-readable reason, free of submitted data.
             */
            message: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LivenessResponse
         * @description Result of a liveness probe. Always cheap and dependency-free.
         */
        LivenessResponse: {
            /**
             * Status
             * @default alive
             * @constant
             */
            status: "alive";
        };
        /**
         * MessageResponse
         * @description A message embedded in a session detail response.
         */
        MessageResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            role: components["schemas"]["MessageRole"];
            /** Content */
            content: string;
            /** Metadata */
            metadata: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * MessageRole
         * @description Author role of a conversation message.
         * @enum {string}
         */
        MessageRole: "user" | "assistant" | "system";
        /**
         * PatientCreate
         * @description Body for ``POST /patients`` (upsert by phone).
         */
        PatientCreate: {
            /**
             * Phone
             * @description Phone number in any format; normalized to E.164.
             */
            phone: string;
            /**
             * Full Name
             * @description Optional display name; updated on an existing patient.
             */
            full_name?: string | null;
        };
        /**
         * PatientResponse
         * @description Single-record patient response, including own-identity fields.
         */
        PatientResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Mrn */
            mrn: string;
            /** Phone */
            phone: string;
            /** Full Name */
            full_name: string;
            status: components["schemas"]["PatientStatus"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * PatientStatus
         * @description Clinical status shown in the CRM reply.
         * @enum {string}
         */
        PatientStatus: "stable" | "admitted" | "critical" | "discharged";
        /**
         * ReadinessResponse
         * @description Aggregate readiness state and the individual dependency checks.
         */
        ReadinessResponse: {
            /**
             * Ready
             * @description True only when every check reports ok.
             */
            ready: boolean;
            /**
             * Checks
             * @description One entry per registered dependency check; empty in Phase 0.
             */
            checks?: components["schemas"]["Check"][];
        };
        /**
         * RootResponse
         * @description Courtesy landing payload returned from ``GET /``.
         */
        RootResponse: {
            /** Name */
            name: string;
            /** Version */
            version: string;
        };
        /**
         * SessionCreate
         * @description Body for ``POST /sessions``.
         */
        SessionCreate: {
            /**
             * Phone
             * @description Optional caller phone; if it resolves, the session is associated.
             */
            phone?: string | null;
            /**
             * Title
             * @description Optional thread title; a default is applied when omitted.
             */
            title?: string | null;
        };
        /**
         * SessionDetailResponse
         * @description Session with optionally embedded messages (``?include=messages``).
         */
        SessionDetailResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Patient Id */
            patient_id: string | null;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Messages
             * @description Present only when messages are requested; otherwise null.
             */
            messages?: components["schemas"]["MessageResponse"][] | null;
        };
        /**
         * SessionResponse
         * @description A conversation thread. Contains no patient PII.
         */
        SessionResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Patient Id */
            patient_id: string | null;
            /** Title */
            title: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * SummarizeResponse
         * @description The result of refreshing a session's rolling summary.
         */
        SummarizeResponse: {
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Summary */
            summary: string | null;
            /** Updated */
            updated: boolean;
        };
        /**
         * TableResponse
         * @description A structured table (the CRM reply) for the frontend to render verbatim.
         */
        TableResponse: {
            /** Columns */
            columns: string[];
            /** Rows */
            rows: string[][];
        };
        /**
         * TraceEntryResponse
         * @description One node's PII-free trace contribution.
         */
        TraceEntryResponse: {
            /** Node */
            node: string;
            /** Data */
            data: {
                [key: string]: unknown;
            };
        };
        /**
         * UsageResponse
         * @description Token, cost, and latency accounting for the synth call.
         */
        UsageResponse: {
            /** Prompt Tokens */
            prompt_tokens: number;
            /** Completion Tokens */
            completion_tokens: number;
            /** Total Tokens */
            total_tokens: number;
            /** Estimated Cost Usd */
            estimated_cost_usd: number;
            /** Latency Ms */
            latency_ms: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessResponse"];
                };
            };
        };
    };
    readiness_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
    config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigResponse"];
                };
            };
        };
    };
    upsert_patient_patients_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatientCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_patients__patient_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_patient_patients__patient_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                patient_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_patient_by_phone_patients_by_phone__phone__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                phone: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PatientResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sessions_sessions_get: {
        parameters: {
            query?: {
                /** @description Caller phone filter. */
                phone?: string | null;
                /** @description Patient id filter. */
                patient_id?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_by_id_sessions__session_id__get: {
        parameters: {
            query?: {
                include?: "messages" | null;
            };
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_session_sessions__session_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_history_chat_history_get: {
        parameters: {
            query: {
                /** @description Session to read. */
                session_id: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatHistoryResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_summarize_chat_summarize_post: {
        parameters: {
            query: {
                /** @description Session to summarize. */
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummarizeResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_clear_memory_chat_memory_delete: {
        parameters: {
            query: {
                /** @description Session to clear. */
                session_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootResponse"];
                };
            };
        };
    };
}
