// Convenience aliases over the OpenAPI-generated component schemas. These are the
// single source of truth for the shapes the UI renders: they are regenerated by
// `npm run gen:api` from the backend's schema, so a Pydantic change surfaces here
// as a TypeScript error rather than a silent runtime mismatch. Do not hand-edit
// shapes here — only alias what `schema.d.ts` already defines.

import type { components } from './schema';

type Schemas = components['schemas'];

export type ChatRequest = Schemas['ChatRequest'];
export type ChatResponse = Schemas['ChatResponse'];
export type TableResponse = Schemas['TableResponse'];
export type UsageResponse = Schemas['UsageResponse'];
export type TraceEntry = Schemas['TraceEntryResponse'];
export type ChatMessage = Schemas['ChatMessageResponse'];
export type ChatHistoryResponse = Schemas['ChatHistoryResponse'];
export type SummarizeResponse = Schemas['SummarizeResponse'];

export type SessionResponse = Schemas['SessionResponse'];
export type SessionDetailResponse = Schemas['SessionDetailResponse'];
export type SessionCreate = Schemas['SessionCreate'];
export type MessageResponse = Schemas['MessageResponse'];
export type MessageRole = Schemas['MessageRole'];

export type PatientResponse = Schemas['PatientResponse'];
export type PatientCreate = Schemas['PatientCreate'];
export type PatientStatus = Schemas['PatientStatus'];

export type ReadinessResponse = Schemas['ReadinessResponse'];
export type LivenessResponse = Schemas['LivenessResponse'];
export type ConfigResponse = Schemas['ConfigResponse'];
export type Check = Schemas['Check'];
export type ErrorEnvelope = Schemas['ErrorEnvelope'];

// The five routes the backend can take. Mirrors `graph.schemas.Route`; the
// backend sends the value as a plain string on `ChatResponse.route`, so this
// alias documents the closed set the UI styles against without constraining the
// wire type.
export type Route = 'crm' | 'rag' | 'direct' | 'web_search';

// Verdict values the pipeline can return on `ChatResponse.verdict`. Mirrors
// `graph.schemas.Verdict`.
export type Verdict = 'proceed' | 'cache_hit' | 'out_of_scope';
